spring.application.name=API_GATEWAY
server.port=3333
eureka.client.serviceUrl.defaultZone=http://localhost:8763/eureka
spring.main.web-application-type=reactive

# Enable API Gateway to automatically route traffic based on services registered in Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true